name: Build and deploy to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack build --target web
      - uses: actions/upload-artifact@master
        with:
            name: wasm-package
            path: pkg
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - run: mkdir web
      - run: cp index.html web
      - run: cp styles.css web
      - uses: actions/download-artifact@master
        with:
          name: wasm-package # from build
          path: web/pkg
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
